# tests_ae_sdk_v2/e2e_phase4/test_ae_register_real_and_emit_phase4.py

import time
import base64

from aegnix_ae.client_v2 import AEClient

ABI_URL = "http://127.0.0.1:8080"

# ======== REAL KEYS GENERATED BY abi_service/enroll_ae.py ========
PHASE4_PRIV_B64 = "g0IBV/EpRyjJO+eDmj4aR78CShLK5O0x39Q1W8nQ6mo="
PHASE4_PUB_B64  = "F61o2yvLAJisbT2J+mm5AUun7cTIZYOaOTv7izAy3fE="

def b64d(x):
    return base64.b64decode(x)


# --------------------------------------------------------------------
# No bootstrap fixture needed — ABI already has the key
# --------------------------------------------------------------------


def test_ae_register_real_and_emit_full():

    ae = AEClient(
        name="phase4_ae",
        abi_url=ABI_URL,
        keypair={
            "priv": b64d(PHASE4_PRIV_B64),
            "pub":  b64d(PHASE4_PUB_B64),
        },
        publishes=["fusion.topic"],
        subscribes=[],
        transport="http",
    )

    # Register with ABI
    assert ae.register_with_abi(), "AE must register successfully."

    # Session received
    assert ae.session is not None
    assert ae.session.access_token is not None
    assert ae.session.refresh_token is not None

    # Emit test message
    ae.emit("fusion.topic", {"track_id": "E2E-FULL-PASS"})

    time.sleep(0.25)

    assert True
